{"cells":[{"cell_type":"code","execution_count":2,"id":"0lNpfbTrSXHK","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"elapsed":12018,"status":"ok","timestamp":1743478464711,"user":{"displayName":"Kuang SU","userId":"15882921308009309791"},"user_tz":420},"id":"0lNpfbTrSXHK","outputId":"9656d024-3d45-41e7-f29d-150769ebaae5"},"outputs":[{"name":"stdout","output_type":"stream","text":["Mounted at /content/drive\n"]}],"source":["from google.colab import drive\n","drive.mount('/content/drive')"]},{"cell_type":"code","execution_count":4,"id":"Gl_p3aTNSnm4","metadata":{"executionInfo":{"elapsed":2,"status":"ok","timestamp":1743478477440,"user":{"displayName":"Kuang SU","userId":"15882921308009309791"},"user_tz":420},"id":"Gl_p3aTNSnm4"},"outputs":[],"source":["import os\n","os.chdir('/content/drive/My Drive/CycleGAN')"]},{"cell_type":"code","execution_count":null,"id":"38HstrUAWpmp","metadata":{"colab":{"background_save":true,"base_uri":"https://localhost:8080/","height":393},"executionInfo":{"elapsed":16317,"status":"error","timestamp":1743478398239,"user":{"displayName":"Kuang SU","userId":"15882921308009309791"},"user_tz":420},"id":"38HstrUAWpmp"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-5-1b03ee5c7a09\u003e\", line 25, in \u003ccell line: 0\u003e\n","    from data import create_dataset\n","  File \"/content/drive/My Drive/CycleGAN/data/__init__.py\", line 6, in \u003cmodule\u003e\n","  File \"/content/drive/My Drive/CycleGAN/data/base_dataset.py\", line 9, in \u003cmodule\u003e\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/__init__.py\", line 10, in \u003cmodule\u003e\n","    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/models/__init__.py\", line 2, in \u003cmodule\u003e\n","    from .convnext import *\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/models/convnext.py\", line 8, in \u003cmodule\u003e\n","    from ..ops.misc import Conv2dNormActivation, Permute\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/ops/__init__.py\", line 23, in \u003cmodule\u003e\n","    from .poolers import MultiScaleRoIAlign\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/ops/poolers.py\", line 10, in \u003cmodule\u003e\n","    from .roi_align import roi_align\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/ops/roi_align.py\", line 7, in \u003cmodule\u003e\n","    from torch._dynamo.utils import is_compile_supported\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/_dynamo/__init__.py\", line 3, in \u003cmodule\u003e\n","    from . import convert_frame, eval_frame, resume_execution\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/_dynamo/convert_frame.py\", line 33, in \u003cmodule\u003e\n","    from torch._dynamo.symbolic_convert import TensorifyState\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/_dynamo/symbolic_convert.py\", line 27, in \u003cmodule\u003e\n","    from torch._dynamo.exc import TensorifyScalarRestartAnalysis\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/_dynamo/exc.py\", line 11, in \u003cmodule\u003e\n","    from .utils import counters\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/_dynamo/utils.py\", line 1752, in \u003cmodule\u003e\n","    if has_triton_package():\n","       ^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/_triton.py\", line 9, in has_triton_package\n","    from triton.compiler.compiler import triton_key\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1176, in _find_and_load\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1138, in _find_and_load_unlocked\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1078, in _find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1507, in find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1476, in _get_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1434, in _path_importer_cache\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","           ^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 1739, in getinnerframes\n","    traceback_info = getframeinfo(tb, context)\n","                     ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 1684, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","               ^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 948, in getsourcefile\n","    module = getmodule(object, filename)\n","             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 980, in getmodule\n","    file = getabsfile(object, _filename)\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 964, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","                            ^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"\u003cfrozen posixpath\u003e\", line 404, in abspath\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-5-1b03ee5c7a09\u003e\", line 25, in \u003ccell line: 0\u003e\n","    from data import create_dataset\n","  File \"/content/drive/My Drive/CycleGAN/data/__init__.py\", line 6, in \u003cmodule\u003e\n","  File \"/content/drive/My Drive/CycleGAN/data/base_dataset.py\", line 9, in \u003cmodule\u003e\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/__init__.py\", line 10, in \u003cmodule\u003e\n","    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/models/__init__.py\", line 2, in \u003cmodule\u003e\n","    from .convnext import *\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/models/convnext.py\", line 8, in \u003cmodule\u003e\n","    from ..ops.misc import Conv2dNormActivation, Permute\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/ops/__init__.py\", line 23, in \u003cmodule\u003e\n","    from .poolers import MultiScaleRoIAlign\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/ops/poolers.py\", line 10, in \u003cmodule\u003e\n","    from .roi_align import roi_align\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/ops/roi_align.py\", line 7, in \u003cmodule\u003e\n","    from torch._dynamo.utils import is_compile_supported\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/_dynamo/__init__.py\", line 3, in \u003cmodule\u003e\n","    from . import convert_frame, eval_frame, resume_execution\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/_dynamo/convert_frame.py\", line 33, in \u003cmodule\u003e\n","    from torch._dynamo.symbolic_convert import TensorifyState\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/_dynamo/symbolic_convert.py\", line 27, in \u003cmodule\u003e\n","    from torch._dynamo.exc import TensorifyScalarRestartAnalysis\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/_dynamo/exc.py\", line 11, in \u003cmodule\u003e\n","    from .utils import counters\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/_dynamo/utils.py\", line 1752, in \u003cmodule\u003e\n","    if has_triton_package():\n","       ^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/_triton.py\", line 9, in has_triton_package\n","    from triton.compiler.compiler import triton_key\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1176, in _find_and_load\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1138, in _find_and_load_unlocked\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1078, in _find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1507, in find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1476, in _get_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1434, in _path_importer_cache\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","           ^^^^^^^^^^^^\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","           ^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 1739, in getinnerframes\n","    traceback_info = getframeinfo(tb, context)\n","                     ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 1684, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","               ^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 948, in getsourcefile\n","    module = getmodule(object, filename)\n","             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 980, in getmodule\n","    file = getabsfile(object, _filename)\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 964, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","                            ^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"\u003cfrozen posixpath\u003e\", line 404, in abspath\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-5-1b03ee5c7a09\u003e\", line 25, in \u003ccell line: 0\u003e\n","    from data import create_dataset\n","  File \"/content/drive/My Drive/CycleGAN/data/__init__.py\", line 6, in \u003cmodule\u003e\n","  File \"/content/drive/My Drive/CycleGAN/data/base_dataset.py\", line 9, in \u003cmodule\u003e\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/__init__.py\", line 10, in \u003cmodule\u003e\n","    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip\n","    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/models/__init__.py\", line 2, in \u003cmodule\u003e\n","    from .convnext import *\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/models/convnext.py\", line 8, in \u003cmodule\u003e\n","    from ..ops.misc import Conv2dNormActivation, Permute\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/ops/__init__.py\", line 23, in \u003cmodule\u003e\n","    from .poolers import MultiScaleRoIAlign\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/ops/poolers.py\", line 10, in \u003cmodule\u003e\n","    from .roi_align import roi_align\n","  File \"/usr/local/lib/python3.11/dist-packages/torchvision/ops/roi_align.py\", line 7, in \u003cmodule\u003e\n","    from torch._dynamo.utils import is_compile_supported\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/_dynamo/__init__.py\", line 3, in \u003cmodule\u003e\n","    from . import convert_frame, eval_frame, resume_execution\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/_dynamo/convert_frame.py\", line 33, in \u003cmodule\u003e\n","    from torch._dynamo.symbolic_convert import TensorifyState\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/_dynamo/symbolic_convert.py\", line 27, in \u003cmodule\u003e\n","    from torch._dynamo.exc import TensorifyScalarRestartAnalysis\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/_dynamo/exc.py\", line 11, in \u003cmodule\u003e\n","    from .utils import counters\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/_dynamo/utils.py\", line 1752, in \u003cmodule\u003e\n","    if has_triton_package():\n","       ^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/_triton.py\", line 9, in has_triton_package\n","    from triton.compiler.compiler import triton_key\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1176, in _find_and_load\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1138, in _find_and_load_unlocked\n","  File \"\u003cfrozen importlib._bootstrap\u003e\", line 1078, in _find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1507, in find_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1476, in _get_spec\n","  File \"\u003cfrozen importlib._bootstrap_external\u003e\", line 1434, in _path_importer_cache\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","           ^^^^^^^^^^^^\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","           ^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","           ^^^^^^^^^^^^\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","          ^^^^^^^^^^^^^^^^^^^^^^^^\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","           ^^^^^^^^^^^^^^^^^^\n","  File \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 1739, in getinnerframes\n","    traceback_info = getframeinfo(tb, context)\n","                     ^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 1684, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","               ^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 948, in getsourcefile\n","    module = getmodule(object, filename)\n","             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 980, in getmodule\n","    file = getabsfile(object, _filename)\n","           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"/usr/lib/python3.11/inspect.py\", line 964, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","                            ^^^^^^^^^^^^^^^^^^^^^^^^^^\n","  File \"\u003cfrozen posixpath\u003e\", line 404, in abspath\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["# Just run this block. Please do not modify the following code.\n","import math\n","import time\n","import io\n","import numpy as np\n","import csv\n","from IPython.display import Image\n","\n","# Pytorch package\n","import torch\n","import torch.nn as nn\n","import torch.optim as optim\n","\n","from torch.utils.data import DataLoader\n","from collections import Counter\n","from torch.nn.utils.rnn import pad_sequence\n","\n","\n","import os\n","import argparse\n","import torch\n","from tqdm import tqdm\n","import numpy as np\n","from PIL import Image\n","from data import create_dataset\n","from models import create_model\n","\n","from util.util import save_images\n","\n","\n","# Tqdm progress bar\n","from tqdm import tqdm_notebook, tqdm\n","\n","# for auto-reloading external modules\n","# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython\n","%load_ext autoreload\n","%autoreload 2"]},{"cell_type":"code","execution_count":null,"id":"vAifquJ6Wr6c","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"vAifquJ6Wr6c","outputId":"c23f80ac-7a1e-4c64-918f-c056aab29d70"},"outputs":[{"name":"stdout","output_type":"stream","text":["You are using device: cpu\n"]}],"source":["# Check device availability\n","device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n","print(\"You are using device: %s\" % device)"]},{"cell_type":"code","execution_count":null,"id":"s3Kr6T_2WwDq","metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"s3Kr6T_2WwDq","outputId":"b5aa9072-417b-48ea-ed75-b82840ddae24"},"outputs":[{"name":"stdout","output_type":"stream","text":["model name\t: Intel(R) Xeon(R) CPU @ 2.20GHz\n","model name\t: Intel(R) Xeon(R) CPU @ 2.20GHz\n"]}],"source":["!cat /proc/cpuinfo | grep 'model name'"]},{"cell_type":"code","execution_count":null,"id":"2du0k4aUYbXO","metadata":{"id":"2du0k4aUYbXO"},"outputs":[],"source":["if __name__ == '__main__':\n","\n","    parser = argparse.ArgumentParser()\n","\n","    parser.add_argument('--dataroot',\n","                        default='./datasets/nature_image',\n","                        help='directory of images to be transferred',\n","                        type=str)\n","    parser.add_argument('--result_dir',\n","                        default='./results',\n","                        help='directory to save images after style transfer',\n","                        type=str)\n","    parser.add_argument('--load_size',\n","                        default=512,\n","                        help='load size of test images',\n","                        type=int)\n","    parser.add_argument('--crop_size',\n","                        default=512,\n","                        help='crop size of test images',\n","                        type=int)\n","    parser.add_argument('--name',\n","                        default='nature2painting',\n","                        help='name of experiment, also where model is stored',\n","                        type=str)\n","\n","    args = parser.parse_args()\n","\n","    dataroot = args.dataroot\n","    results_dir = args.result_dir\n","    load_size = args.load_size\n","    crop_size = args.crop_size\n","    name = args.name\n","\n","\n","    dataset = create_dataset(dataroot, batch_size=1, phase='test', load_size=load_size, crop_size=crop_size, serial_batches=True, input_nc=3, output_nc=3, no_flip = True)\n","    model = create_model(isTrain=False, name=name, model='test')\n","    model.setup()\n","\n","\n","    for i, data in enumerate(tqdm(dataset)):\n","\n","        model.set_input(data)\n","        model.test()\n","        visuals = model.get_current_visuals()\n","        img_path = model.get_image_paths()\n","\n","        save_images(visuals, results_dir, img_path, name=str(i))\n"]}],"metadata":{"colab":{"name":"","version":""},"kernelspec":{"display_name":"Python 3 (ipykernel)","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.10.16"}},"nbformat":4,"nbformat_minor":5}